internal/api/types.go
internal/sources/plex.go

The url is stored, so it should be possible to load it as an image in fyne. Closes #27.

feat(plex): add film thumbnail url for films

---

frontend/fyne.go
internal/api/types.go
internal/connection/connection.go
internal/middle/middle_to_back.go
internal/middle/middle_to_front.go
internal/middle/users.go

Adds framework for middle and back to work on

32 mb connection

---

internal/sources/cache.go
internal/sources/plex.go

Feature: cache source interests

---

frontend/fyne.go
internal/api/types.go
internal/middle/middle_to_front.go
internal/middle/users.go
internal/personal/personal.go
internal/sources/plex.go
internal/sources/sources.go

Loads personal data, and creates "self"
Gets interests

Added init function to middle

---

internal/middle/middle_to_front.go
internal/middle/users.go
internal/personal/personal.go
internal/personal/uuid.go

Moved self (contains personal data) from middle to personal, to avoid circular imports

feat: Move self to personal

---

frontend/fyne.go
internal/middle/middle_to_front.go

to avoid circular imports, middle's Pass function is called in frontend's Main function, which gives the middle access to refresh friends and refresh user functionality.

feat: added Pass function to connect middle and front

---

.github/workflows/main.yml
.gitignore
Makefile
README.md

feat: add android build

---

frontend/fyne.go
internal/middle/middle_to_front.go

- added friend request tab on UI which shows the outgoing and incoming friend requests
- links to middle API for accepting and rejecting friend requests

Show friend requests in UI

---

frontend/fyne.go
internal/personal/personal.go

Merge the login form feature into main.

feat:added login form and fixed out of date main branch

---

internal/api/types.go
internal/middle/middle_to_front.go
internal/middle/users.go

Changed ranked_users from a priority queue to a sorted list, and added functions:
- addUser(user api.User): Adds a user to the users map, and inserts it into the sorted ranked_users
- removeUser(id api.ID): Removes user with UserID=id from users, and ranked_users

refactor: Changed priority queue to sorted list

---

frontend/fyne.go

fix: avoid crash if interest image is nil

---

frontend/fyne.go
internal/middle/users.go

- fixed bug which caused outgoing friend request list to not update after the other end accepted your friend request
- added interests and names appropriately to Peers tab, Friends Tab and Friend Requests tabs
- looks through interests in peers discovered and shows image of first interest with an image, and no images if none

Feat/formatted friend UI

---

.github/workflows/main.yml

The format check will now fail if files are incorrectly formatted
Closes #96

ci: fix format check not doing anything

---

frontend/fyne.go
internal/connection/connection.go
internal/middle/middle_to_front.go
internal/middle/users.go
internal/personal/personal.go
internal/personal/uuid.go
internal/sources/manual.go
internal/sources/sources.go
internal/storage/storage.go
main.go

User name and interests are now saved for future sessions. If the user has already logged in, they won't be required to fill out the login form again.

Feat: save user data from login form

---

internal/api/types.go
internal/middle/middle_to_front.go
internal/middle/users.go
internal/storage/friend_json.go
internal/storage/storage.go

Fixed persistent storage
When a new friend is created, it now stores it immediately
Now checks if a user is already a stored friend before adding them to users

117 save friends

---

frontend/fyne.go
internal/middle/middle_to_front.go

Made hubs tab which include list of messages and form enter messages and functions for middle to call.

Feat/create hubs UI

---

hub/storage/message_storage.go
internal/api/types.go

Added storage of messages, and message timestamps

feat: Added storage of messages functions

---

frontend/fyne.go
internal/middle/middle_to_front.go
internal/middle/users.go

feature: merge peers and friend requests tabs

---

frontend/fyne.go
internal/api/types.go
internal/middle/middle_to_front.go
internal/personal/personal.go
internal/storage/friend_json.go
main.go

feat: display contact information to friends.

---

frontend/fyne.go
internal/middle/hubs.go
internal/middle/middle_to_front.go
internal/middle/start.go

Adds middle functions to keep track of hubs
Adds function that frontend calls to send message

151 feat create middle hub implementation

---

frontend/fyne.go

Somehow we could end up with accept friend request disabled

fix: reenable send button on incoming request
